### ISSUE TITLE
folder

### ISSUE THREAD

**Issue by suzanakarim** [czaj/DCE#94]
Hi, I am looking for DCE and DCE_tools folder, specifically where can I find the functions (e.g. DataClean)

**Comment by czaj** [comment]
Please see the Tools package: https://github.com/czaj/Tools - it is used by the DCE (you probably want DataCleanDCE.m).

**Comment by suzanakarim** [comment]
Thank you.
I am trying to loading my DCE data into matlab to Latent class analysis. I
found the location of tools folder.

suzana
